server.port=8080

flightlabs.api.key=YOUR_API_KEY
flightlabs.base.url=https://app.goflightlabs.com

spring.datasource.url=jdbc:postgresql://localhost:5432/flights
spring.datasource.username=postgres
spring.datasource.password=yourpassword

spring.jpa.hibernate.ddl-auto=update